// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_matrix_X_l
NumericMatrix make_matrix_X_l(NumericVector p, NumericVector kappa);
RcppExport SEXP CKMRsim_make_matrix_X_l(SEXP pSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(make_matrix_X_l(p, kappa));
    return rcpp_result_gen;
END_RCPP
}
// read_mendel_outped
List read_mendel_outped(CharacterVector Input, IntegerVector NumA);
RcppExport SEXP CKMRsim_read_mendel_outped(SEXP InputSEXP, SEXP NumASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type Input(InputSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NumA(NumASEXP);
    rcpp_result_gen = Rcpp::wrap(read_mendel_outped(Input, NumA));
    return rcpp_result_gen;
END_RCPP
}
// samp_from_mat
IntegerVector samp_from_mat(NumericMatrix M);
RcppExport SEXP CKMRsim_samp_from_mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(samp_from_mat(M));
    return rcpp_result_gen;
END_RCPP
}
