// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_matrix_X_l
NumericMatrix make_matrix_X_l(NumericVector p, NumericVector kappa);
RcppExport SEXP CKMRsim_make_matrix_X_l(SEXP pSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(make_matrix_X_l(p, kappa));
    return __result;
END_RCPP
}
