# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute the matrix X_l given allele frequencies and kappa
#'
#' Ha! I did this initially using R straight up and even tried to make
#' it reasonably vectorized, but the damn thing took forever and was
#' incredible space-inefficient. Ergo, we are going after it using
#' Rcpp.  The genotypes are ordered in rows and columns in the way
#' as described in the paper.
#' @param p vector of allele frequencies
#' @param kappa a 3-vector of the Cotterman coefficients
make_matrix_X_l <- function(p, kappa) {
    .Call('CKMRsim_make_matrix_X_l', PACKAGE = 'CKMRsim', p, kappa)
}

#' pick the genotypes out of the Mendel output pedigree file to use to compute Q
#'
#' Not sure exactly how I am going to do this, as we need to include genotyping error on there as well.
#' Crap.  But at least I have a start on how to parse this monstrous file. This assumes that the focal pair
#' of individuals are labeled 1 and 2.
#' @param Input the path to the Mendel output file to read in.
#' @param NumA the number of alleles at each locus
#' @examples
#' read_mendel_outped("/Users/eriq/Desktop/mendel-example-Ped.out")
read_mendel_outped <- function(Input, NumA) {
    .Call('CKMRsim_read_mendel_outped', PACKAGE = 'CKMRsim', Input, NumA)
}

#' Sample 1 observation from cell probabilities that are columns of a matrix
#'
#' Takes a matrix in which rows sum to one. For each row, performs a
#' single multinomial draw from amongst the columns, weighted by their values in that column
#'
#' @param M a matrix whose rows are reals, each summing to one
#'
#' @return a vector length = \code{nrow(M)} of indices, with each element being
#' the column that was chosen in that row's sampling
#' @export
samp_from_mat <- function(M) {
    .Call('CKMRsim_samp_from_mat', PACKAGE = 'CKMRsim', M)
}

