# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute the matrix X_l given allele frequencies and kappa
#'
#' Ha! I did this initially using R straight up and even tried to make
#' it reasonably vectorized, but the damn thing took forever and was
#' incredible space-inefficient. Ergo, we are going after it using
#' Rcpp.  The genotypes are ordered in rows and columns in the way
#' as described in the paper.
#' @param p vector of allele frequencies
#' @param kappa a 3-vector of the Cotterman coefficients
make_matrix_X_l <- function(p, kappa) {
    .Call('CKMRsim_make_matrix_X_l', PACKAGE = 'CKMRsim', p, kappa)
}

